### ISSUE TITLE
osmarender

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/osm100#6]
osmarender was a big huge project, which probably had many people contributing to it who didn't contribute elsewhere. Not having this probably causes significant differences with 2007-2010 stats.

I had a go at converting from SVN but
- reposurgeon doesn't work with SVN repository format 7, only 6 (https://gitlab.com/esr/reposurgeon/issues/37)
- svn-to-git did this as a 30k commit repo, most of which didn't change anything
- osmarender has moved directories a few times (https://trac.openstreetmap.org/browser/subversion/applications/rendering/osmarender/README.txt?rev=10000)

To get contributor statistics, it's essential to map SVN IDs to emails, which is independent of tools.

If we can get the contributor mapping, I'm tempted to convert all of SVN to git with reposurgeon, even if it duplicates some other projects, because we just aggregate them all

**Comment by gravitystorm** [comment]
You should talk to @tomhughes about this kind of thing, since he has a well-practised method to convert OSM SVN repos to git repos, including the correct mapping of svn id to emails.

Note that in the cases where we've ended up with SVN ids in the git repo, it's possible to add them to the duplicates list e.g. `framm@0c6e7542-c601-0410-84e7-c038aed88b3b`

**Comment by tomhughes** [comment]
I already gave @pnorman my (partial) mapping file.

If there are other ones missing them I can try and look them up in my email which should work unless they are very early users.

**Comment by tomhughes** [comment]
This is an example of the script I use (for a simple repo with no branches):

``` sh
#!/bin/sh

git svn init --trunk=tirex http://svn.openstreetmap.org/applications/utils

git svn fetch --authors-file=/home/tom/src/osm/svn2git/git-authors

git checkout master

export PATH=$PATH:/home/tom/src/osm/svn2git/git-svn-abandon

git svn-abandon-fix-refs
git svn-abandon-cleanup

git gc
git prune
git gc
```

The `git-svn-abandon` bits can be ignored if you're going to throw the repo away. They just get rid of the links back to svn if you're doing a permanent migration.

**Comment by tomhughes** [comment]
Oh, note my script will abort when it finds an unmapped user, which can result in going around in circles a lot until you find all the users ;-)

**Comment by pnorman** [comment]
> Note that in the cases where we've ended up with SVN ids in the git repo, it's possible to add them to the duplicates list e.g. framm@0c6e7542-c601-0410-84e7-c038aed88b3b

Because some of the repos (josm plugins) are live svn to git mirrors, I think I'm going to end up expanding the duplicates list significantly.

**Comment by gravitystorm** [comment]
I'm not sure where the git conversion project ended up, but feel free to add a PR if the repo is now available somewhere.
